# Generated by Django 6.0.3 on 2026-04-30 11:56

import freeradius.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(max_length=128)),
                ('shortname', models.CharField(max_length=32)),
                ('type_nas', models.CharField(db_column='type', default='other', max_length=30)),
                ('ports', models.IntegerField()),
                ('secret', models.CharField(default='secret', max_length=60)),
                ('server', models.CharField(max_length=64)),
                ('community', models.CharField(max_length=50)),
                ('description', models.CharField(default='RADIUS Client', max_length=200)),
            ],
            options={
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NasreloadModel',
            fields=[
                ('nasipaddress', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('reloadtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'nasreload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadacctModel',
            fields=[
                ('radacctid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(default='', max_length=64)),
                ('acctuniqueid', models.CharField(default='', max_length=32)),
                ('rad_username', models.CharField(db_column='username', default='', max_length=64)),
                ('realm', models.CharField(default='', max_length=64)),
                ('nasipaddress', models.CharField(default='', max_length=15)),
                ('nasportid', models.CharField(default=None, max_length=32)),
                ('nasporttype', models.CharField(default=None, max_length=32)),
                ('acctstarttime', models.DateTimeField(default=None)),
                ('acctupdatetime', models.DateTimeField(default=None)),
                ('acctstoptime', models.DateTimeField(default=None)),
                ('acctinterval', models.IntegerField(default=None)),
                ('acctsessiontime', models.IntegerField(default=None)),
                ('acctauthentic', models.CharField(default=None, max_length=32)),
                ('connectinfo_start', models.CharField(default=None, max_length=128)),
                ('connectinfo_stop', models.CharField(default=None, max_length=128)),
                ('acctinputoctets', models.BigIntegerField(default=None)),
                ('acctoutputoctets', models.BigIntegerField(default=None)),
                ('calledstationid', models.CharField(default='', max_length=50)),
                ('callingstationid', models.CharField(default='', max_length=50)),
                ('acctterminatecause', models.CharField(default='', max_length=32)),
                ('servicetype', models.CharField(default=None, max_length=32)),
                ('framedprotocol', models.CharField(default=None, max_length=32)),
                ('framedipaddress', models.CharField(default='', max_length=15)),
                ('framedipv6address', models.CharField(default='', max_length=45)),
                ('framedipv6prefix', models.CharField(default='', max_length=45)),
                ('framedinterfaceid', models.CharField(default='', max_length=44)),
                ('delegatedipv6prefix', models.CharField(default='', max_length=45)),
                ('rad_class', models.CharField(db_column='class', default=None, max_length=64)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadcheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad_username', models.CharField(db_column='username', default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', freeradius.models.FixedCharField(default='==', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadgroupcheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', freeradius.models.FixedCharField(default='==', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'db_table': 'radgroupcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadgroupreplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', freeradius.models.FixedCharField(default='=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadpostauthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad_username', models.CharField(db_column='username', default='', max_length=64)),
                ('rad_pass', models.CharField(db_column='pass', default='', max_length=64)),
                ('reply', models.CharField(default='', max_length=64)),
                ('authdate', models.DateTimeField(auto_now_add=True)),
                ('rad_class', models.CharField(db_column='class', default=None, max_length=64)),
            ],
            options={
                'db_table': 'radpostauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadreplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad_username', models.CharField(db_column='username', default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', freeradius.models.FixedCharField(default='=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadusergroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad_username', models.CharField(db_column='username', default='', max_length=64)),
                ('groupname', models.CharField(default='', max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
    ]
